luxbsa/luxbsa/Controllers/MeetingController.cs
using luxbsa.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace luxbsa.Controllers
{
    [Authorize]
    [BaseSessionFilterAttribute]
    public class MeetingController : Controller
    {
        //
        // GET: /Meeting/

        public ActionResult Index()
        {
            return View();
        }

    }
}

luxbsa/luxbsa/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace luxbsa.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        //
        // GET: /Message/

        public ActionResult Index()
        {
            return View();
        }

    }
}

luxbsa/luxbsa/Views/Shared/_Anonymous.cshtml
<!DOCTYPE html>
<html>
<head>
  @Html.Partial("_Head")
  @*@Styles.Render("~/StyleBundle/css")*@
</head>
@* style="background-color: #2a2e36"    class="clearfix" data-smooth-scrolling="1"    *@
<body class="clearfix background-2" data-smooth-scrolling="1">

  <!-- Busy Indicator -->
  <div id="loading" class="alpha">
    <img src="../../Content/img/busy.gif" alt="" />
  </div>

  <div class="vc_body">
    @RenderBody()


    @Scripts.Render("~/js/Global")
    @Scripts.Render("~/js/Specific/MetroSlider")

    <script src="~/Scripts/jquery.signalR-2.0.2.js"></script>
    <script src="~/signalr/hubs"></script>

    @Html.Partial("_GlobalPartial")

    @Html.Partial("_FooterPartial")

    @RenderSection("scripts", required: false)
  </div>

  @*<a class="back-top visible" href="#" id="back-top"><i class="fa fa-chevron-up icon-white"></i></a>*@





</body>


</html>

luxbsa/luxbsa/Views/Shared/_FooterPartialAuth.cshtml
<footer class="footer-2 mode-3">
  <div class="vc_bottom background-10">
    <div class="wrapper">
      <div class="container">
        <div class="vc_footer-line"> </div>
        <div class="bg">
          <div class="row">
            <div class=" col-sm-12 col-md-6">
              <div class="copyright pull-left">
                <h5> Copyright &copy;2014 LUX-BSA (PTY) LTD. All Rights Reserved </h5>
              </div>
            </div>
            <div class="col-sm-12 col-md-6">
              <div class="menu pull-right"> 
                <a href="#"> FAQ </a> 
                <a href="#"> Contact </a>                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

luxbsa/luxbsa/Views/Shared/_GlobalPartial.cshtml
<div id="message_box-modal" class="modal fade" tabindex="-1" role="dialog">
</div>

<!-- Notification Modal -->
<script id="message_box" type="text/html">
  <div class="modal-dialog {{ModalType}}">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>{{Title}}</h4>
      </div>
      <div class="modal-body row">
        <div class="col-md-4">
          <div class="form-group">
            <img class="logo" src="@Url.Content("~/Content/img/logo/logo_original.png")" />
            <i>Connecting every small, medium and large sized corporation in Africa by stretching all obtained information and technology to the rest of the undeveloped but potential regions.</i>
          </div>
          <div class="form-group">
            <ul>
              <li><a href="javascript:void(0)" onclick="footer.contact_OnClick();">Contact Us</a></li>
              {{^Terms}}<li><a href="javascript:void(0)" onclick="footer.terms_OnClick();">Terms & Conditions</a></li>{{/Terms}}
            </ul>
          </div>
        </div>
        <div class="col-md-8 modal-body-height-auto message_box-content
          {{#AlertType.Success}}alert alert-success{{/AlertType.Success}}
          {{#AlertType.Danger}}alert alert-danger{{/AlertType.Danger}}">
          {{{Content}}}
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="modal-footer">
        <a class="vc_btn vc_btn-inverse btn-small" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</script>

<script id="simple_message_box" type="text/html">
  <div class="modal-dialog {{ModalType}}">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>{{Title}}</h4>
      </div>
      <div class="modal-body">        
        <div 
          class="modal-body-height-auto message_box-content clearfix 
          {{#AlertType.Success}}alert alert-success{{/AlertType.Success}}
          {{#AlertType.Danger}}alert alert-danger{{/AlertType.Danger}}" >
          {{{Content}}}
        </div>
      </div>
      <div class="modal-footer">
        <a class="vc_btn vc_btn-inverse btn-small" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</script>

<script>
  var global = {};

  (function () {
    global.showBusy = function () {
      $("#loading").show();
    }

    global.hideBusy = function () {
      $("#loading").hide();
    }

    $.ajaxSetup({
      beforeSend: function () {
        global.showBusy();
      },
      complete: function () {
        global.hideBusy();
      },
      error: function (oData) {
        $('.modal').modal('hide');
        global.hideBusy();
        global.showSimpleMessageBox('Oops..! An error has occured. <br /> Please <a href="javascript:void(0)" onclick="footer.contact_OnClick();">click here</a> to contact us. <br /><br /> Thank you', 'LUX-BSA ERROR!', null, false, { Danger: true });
      }
    });

    var _maxHeight;
    function messageBox(messageBox, maxHeight) {
      global.expandModalHeight = maxHeight;
      $('#message_box-modal').html(messageBox)
      $('#message_box-modal').modal('show');

      if (global.expandModalHeight == true) {
        $('.message_box-content').css('height', $(window).height() - 250);
      }
    }

    global.showMessageBox = function (content, title, modalType, maxHeight, alertType, terms) {
      debugger;
      var template = {
        Title: title,
        Content: content,
        ModalType: modalType,
        AlertType: alertType,
        Terms: terms === true ? terms : false
      }      
      var messageBoxTeplate = ich.message_box(template, true);
      messageBox(messageBoxTeplate, maxHeight);
    }

    global.showSimpleMessageBox = function (content, title, modalType, maxHeight, alertType) {
      var template = {
        Title: title,
        Content: content,
        ModalType: modalType,
        AlertType: alertType
      }
      var messageBoxTeplate = ich.simple_message_box(template, true);
      messageBox(messageBoxTeplate, maxHeight);
    }

    

    global.notification = $.connection.notificationHub;

    $.connection.hub.start().done(function () {
      //init hubs
      global.notification.server.init();
    });

    global.notification.client.GetConnectionId = function (connectionId) {
      global.notificationConnectionId = connectionId;
    }


    global.onPageLoad = function () {
      //$('#message_box-modal').on('shown.bs.modal', function (e) {
        
      //})      
    }

  }());

  $(document).ready(function () {
    themeJs.ready($);
    global.onPageLoad();
    global.hideBusy();
  });
  $(window).load(function () {
    themeJs.load();
  });
</script>

luxbsa/luxbsa/Views/Shared/_Head.cshtml
<meta charset="utf-8" />
<!-- Set the viewport width to device width for mobile -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="luxbsa" />
<meta name="description" content="LuxBsa">

<title>@ViewBag.Title</title>

<!-- Fav and touch icons -->
@*<link rel="apple-touch-icon-precomposed" sizes="144x144" href="Content/img/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="Content/img/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="Content/img/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="Content/img/ico/apple-touch-icon-57-precomposed.png">*@
<link rel="shortcut icon" href="@Url.Content("/favicon.ico")">

    
@Styles.Render("~/StyleBundle/themes/base/css")

@Styles.Render("~/StyleBundle/Bootstrap")
@Styles.Render("~/StyleBundle/JQuery-ui")
@Styles.Render("~/StyleBundle/Fonts")
    
@Styles.Render("~/StyleBundle/Plugin")
@Styles.Render("~/StyleBundle/Theme")
<!--[if IE]>@Styles.Render("~/StyleBundle/IE")<![endif]-->
@Styles.Render("~/StyleBundle/DesignMode")
@Styles.Render("~/StyleBundle/Responsive")
@Styles.Render("~/StyleBundle/Custom")

@Scripts.Render("~/js/Modernizr")
<!--[if lt IE 9]>@Scripts.Render("~/js/IE8HTML5")<![endif]-->

luxbsa/luxbsa/Views/Shared/_HeaderSecondary.cshtml
<div class="vc_secondary-menu-wrapperA">
  <div class="container">
      <div class="vc_secondary-menu">
        <div class="vc_social-share-wrappe pull-right">
          <div class="vc_contact-top" style="display:inline-block">
            <div class="pull-right" style="margin-right:20px">
              <h5><span style="font-size: 1.1em;">Already Have an Account With: </span></h5>
            </div>
          </div>      
          <div class="vc_social-share vc_tight vc_grey-color vc_border-top " style="display:inline-block;">
            <a title="Twitter" class="twitter" href="#"><i class="fa fa-twitter"></i></a>
          </div>
          
        </div>
      </div>
  </div>
</div>

luxbsa/luxbsa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  @Html.Partial("_Head")
  <link href="@Url.Content("~/Content/themes/tympanus/slidemenu.css")" rel="stylesheet" />
  <link href="@Url.Content("~/Content/themes/folder/css/style.css")" rel="stylesheet" />
  @*<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" />*@
  @*<link href="@Url.Content("~/Content/themes/folder/css/skin.css")" rel="stylesheet" />*@
  <link href="@Url.Content("~/Content/themes/bootstrap/typeahead.js-bootstrap.css")" rel="stylesheet" />
  @Styles.Render("~/StyleBundle/css")

</head>
<body class="cbp-spmenu-push background-10">



  <header data-active="features" class="header-3 mode-1" id="header">

    @*@Html.Partial("_HeaderSecondary")*@

    <div class="vc_primary-menu-wrapper background-10">
      <div class="container">
        <div class="row">
          <nav class="vc_menu">
            <div class="logos" style="position: absolute;">
              <span style="font-size: 3em; float: left; margin-top: 25px"><span class="vc_main-color">LUX-BSA</span>
              </span>

            </div>
            <div class="vc_btn-navbar">
              <button type="button" class="btn btn-navbar navbar-toggle" data-toggle="collapse" data-target=".vc_primary-menu"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
            </div>

            <div class="vc_primary-menu pull-right">
              <ul>
                <li>
                  <div class="vc_menu-search-wrapper">
                    <form class="vc_menu-search">
                      <input type="text" name="search" class="vc_menu-search-text" required placeholder="Search">
                      <div class="vc_menu-search-submit"></div>
                    </form>
                  </div>
                </li>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Scout", "Index", "Scout")</li>
                <li>@Html.ActionLink("Board Room", "Index", "Meeting")</li>
                <li>@Html.ActionLink("Messages", "Index", "Message")</li>
                <li>
                  <a>Logged in as <strong class="vc_main-color">@Session["User.FirstName"]</strong> <i class="fa fa-caret-down"></i></a>
                  <div class="vc_menu-open-left vc_menu-2-v">
                    <ul class="clearfix">
                      <li>@Html.ActionLink("User Profile", "UserProfile", "Profile")</li>
                      <li>@Html.ActionLink("Business Profile", "BusinessProfiles", "Profile")</li>
                      <li><a href="@Url.Action("Logout", "Account")">Log out</a></li>
                    </ul>
                  </div>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </header>



  <div class="vc_body">
    @RenderBody()

    @Scripts.Render("~/js/Global")
    @Scripts.Render("~/js/JQueryVal")
    @Scripts.Render("~/js/Specific/Typeahead")
    @Scripts.Render("~/js/Specific/Classie")

    <script src="~/Scripts/jquery.signalR-2.0.2.js"></script>
    <script src="~/signalr/hubs"></script>

    @Html.Partial("_GlobalPartial")

    @Html.Partial("_FooterPartial")

  </div>





  <script>

    $(document).ready(function () {
      //alert("hello 2");
    });
  </script>

  @RenderSection("scripts", required: false)


</body>
</html>